// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIiZEZOsIpCS2IFN-4xxv8XhZJksWJDYc',
    appId: '1:44502753426:web:639abcd4fed66ac044064b',
    messagingSenderId: '44502753426',
    projectId: 'amst-flutter-db-4',
    authDomain: 'amst-flutter-db-4.firebaseapp.com',
    databaseURL: 'https://amst-flutter-db-4-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-4.appspot.com',
    measurementId: 'G-W5L32P1GBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-krToNddojKWeWP-ZQQUyssw-ktqSEkc',
    appId: '1:44502753426:android:f6a6c82c2788b66b44064b',
    messagingSenderId: '44502753426',
    projectId: 'amst-flutter-db-4',
    databaseURL: 'https://amst-flutter-db-4-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Nqh-YcAO1bxWbvjWhSgGE5R4rN5S6HY',
    appId: '1:44502753426:ios:e65798879e4525d344064b',
    messagingSenderId: '44502753426',
    projectId: 'amst-flutter-db-4',
    databaseURL: 'https://amst-flutter-db-4-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-4.appspot.com',
    iosBundleId: 'com.example.appFlutterDb4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Nqh-YcAO1bxWbvjWhSgGE5R4rN5S6HY',
    appId: '1:44502753426:ios:28c49da4d3d7a73544064b',
    messagingSenderId: '44502753426',
    projectId: 'amst-flutter-db-4',
    databaseURL: 'https://amst-flutter-db-4-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-4.appspot.com',
    iosBundleId: 'com.example.appFlutterDb4.RunnerTests',
  );
}
